// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Dashboard: typeof import('./../components/Dashboard.vue')['default']
    TheFirstPage: typeof import('./../components/TheFirstPage.vue')['default']
    TheHomeNav: typeof import('./../components/TheHomeNav.vue')['default']
    TheSideBar: typeof import('./../components/TheSideBar.vue')['default']
  }
}

export { }
