// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Dashboard: typeof import('./../components/Dashboard.vue')['default']
    TheBreadcrumb: typeof import('./../components/TheBreadcrumb.vue')['default']
    TheCreateFoodListCard: typeof import('./../components/TheCreateFoodListCard.vue')['default']
    TheCreateFtyCard: typeof import('./../components/TheCreateFtyCard.vue')['default']
    TheCreateMlistCard: typeof import('./../components/TheCreateMlistCard.vue')['default']
    TheCreateMtyCard: typeof import('./../components/TheCreateMtyCard.vue')['default']
    TheFirstPage: typeof import('./../components/TheFirstPage.vue')['default']
    TheHomeNav: typeof import('./../components/TheHomeNav.vue')['default']
    TheSideBar: typeof import('./../components/TheSideBar.vue')['default']
    TheTagsView: typeof import('./../components/TheTagsView.vue')['default']
  }
}

export { }
